services:
  - type: web
    name: artful-connective-hub
    env: static
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 18.19.0
    routes:
      - type: rewrite
        source: /*
        destination: /index.html